---
# Configure nginx and setup app dir along with default host. Restart nginx.

- name: Create directories
  file: path=/home/deploy/var/www/ state=directory owner=deploy mode=0755

- name: Setup default nginx directory
  file: path=/home/deploy/var/www/{{ default_host }}/html state=directory mode=0755

- name: Setup default nginx page
  template: src=templates/index.html dest=/home/deploy/var/www/{{ default_host }}/html/index.html owner=deploy mode=0644

- name: Copy nginx sites-available file
  become: yes
  command: cp /etc/nginx/sites-available/default /etc/nginx/sites-available/{{ default_host }}

- name: Fill {{ default_host }} nginx config file
  become: yes
  template: src=templates/{{ default_host }} dest=/etc/nginx/sites-available/{{ default_host }}

- name: Symlink sites-available to sites-enabled
  become: yes
  file: src=/etc/nginx/sites-available/{{ default_host }} dest=/etc/nginx/sites-enabled/{{ default_host }} state=link force=yes

- name: Add virtual host to nginx
  become: yes
  template: src=templates/{{ app_name }} dest=/etc/nginx/sites-available/{{ app_name }}

- name: Create symlink from sites-available to sites-enabled
  become: yes
  file:
    src: /etc/nginx/sites-available/{{ app_name }}
    dest: /etc/nginx/sites-enabled/{{ app_name }}
    state: link
  notify:
    - restart nginx

- name: Remove default nginx config
  become: yes
  file: path=/etc/nginx/sites-enabled/default state=absent
  notify:
    - restart nginx

