- name: Create capistrano 3 infrastructure for application
  hosts: 127.0.0.1
  connection: local
  roles:
    - role: capistrano

- name: Configure Nginx for app
  hosts: rails
  remote_user: deploy
  roles:
    - role: app

- name: Add Rails app database and user
  hosts: rails
  remote_user: deploy
  roles:
    - role: rails_db

- name: Upload DB
  hosts: rails
  remote_user: deploy
  roles:
    - role: upload_db

- name: Cron tasks for backup
  hosts: rails
  remote_user: deploy
  roles:
    - role: cron_backup
