---

- name: Install curl
  apt: name=curl

- name: Add locale variables to .bashrc
  become_user: root
  become: yes
  lineinfile:
    dest: /etc/environment
    line: "{{ item.line }}"
  with_items:
    - { line: LC_ALL=en_US.UTF-8 }
