---
- hosts: static
  remote_user: deploy
  tasks:
  - name: Setup default nginx directory
    file: path=~/var/www/middleman.dev/html state=directory mode=0755

  - name: Setup default nginx page
    template: src=../templates/index.html dest=~/var/www/middleman.dev/html/index.html owner=deploy mode=0644

  - name: Copy nginx sites-available file
    become: true
    command: cp /etc/nginx/sites-available/default /etc/nginx/sites-available/middleman.dev

  - name: Fill middleman.dev nginx config file
    become: true
    template: src=../templates/middleman.dev dest=/etc/nginx/sites-available/middleman.dev

  - name: Symlink sites-available to sites-enabled
    become: true
    file: src=/etc/nginx/sites-available/middleman.dev dest=/etc/nginx/sites-enabled/middleman.dev state=link force=yes

  - name: Remove default nginx config
    become: true
    file: path=/etc/nginx/sites-enabled/default state=absent
    notify:
      - restart nginx

  handlers:
    - name: restart nginx
      become: true
      service: name=nginx state=restarted
