---
- hosts: static
  remote_user: deploy
  roles:
    - role: rvm_io.rvm1-ruby
      become: true
      rvm1_rubies:
        - 'ruby-2.3.1'
  tasks:
    - name: Set ruby default
      shell: 'bash -lc "rvm use 2.3.1 --default"'
